### ISSUE TITLE
If a test throws an exception, happyJS submits the form

### ISSUE THREAD

**Issue by chriserickson** [HenrikJoreteg/Happy.js#65]
There is no error handling, so if a test on an attribute throws an exception, the form gets submitted. 

While the bug is clearly elsewhere (the test throwing the exception) this is really hard to debug because the page navigates before the exception can be seen.

**Comment by btpoe** [comment]
Once a script throws an error, the entire script stops running. So if a test throws an error, the script dies before happy can tell the submit event to cancel.

That being said, I just pushed a update that if you pass `testMode: true`, the submit is prevented _before_ running the tests. I would encourage you to only use this if you are trying to debug a test that is throwing an error since with `testMode` on, the submit event is **always** prevented (even if all tests pass).
